# Generated by Django 4.2.6 on 2023-10-24 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="updated_at",
        ),
    ]
