# Generated by Django 4.2.6 on 2023-10-26 15:13

from django.db import migrations, models
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(upload_to=quizzes.models.image_file_path),
        ),
    ]
