# Generated by Django 4.2.6 on 2023-10-26 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0004_remove_quiz_updated_at_alter_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
