# Generated by Django 4.2.6 on 2023-10-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
