# Generated by Django 4.2.6 on 2023-10-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=models.CharField(max_length=50),
        ),
    ]
